### ISSUE TITLE
[FEATURE] Only one tunnel per UE is supported for now

### ISSUE THREAD

**Issue by BENHSU0723** [HewlettPackard/PacketRusher#111]
Hello, I am trying to build second or more PDU sessions per UE under one Gnb. But I encountered the error message `WARN[0002] [GNB][GTP] Only one tunnel per UE is supported for now, no tunnel will be created for second PDU Session of given UE`, then i comment these check lines and tried again. Below is the error I got.

`FATA[0012] [GNB][GTP] Unable to create Kernel GTP interface: listen udp 192.168.56.103:2152: bind: address already in use0000000003val0000000003 `

**The IP addrress "192.168.56.103" is my Gnb IP. When I try to build second PDU session, this error will show up. I think these below function would build a new interface and bind with UDP port:2152 then managed by vrf device. Do you have any idea or know how to fix this problem?** Please tell me, thank you!! I will apprecaite if you can answer me, maybe I can help to add this feature.

```
go func() {
			// This function should not return as long as the GTP-U UDP socket is open
			if err := gtpLink.CmdAdd(nameInf, 1, ueGnbIp.String(), stopSignal); err != nil {
				log.Fatal("[GNB][GTP] Unable to create Kernel GTP interface: ", err, msin, nameInf)
				return
			}
		}()
```

BRs, Ben

**Comment by linouxis9** [comment]
Hi @BENHSU0723!

Thanks a lot for your message. The error you are getting is the very reason why we are only able to have one UE per gNodeB. We can only have one GTP interface per N3 IP.

There are a few alternatives to this issue:
- Use a single interface for all UEs / PDU Sessions per gNodeB, and then use ip policies to steer the traffic instead of VRF. This solution does work, but is not very performant as all UEs/PDU Sessions will share the max bandwidth.
- Do not support multi UEs / PDU Sessions under a single gNodeB, and force the usage of multiple gNodeB  (which is the solution we sadly opted for, for now, for performance reasons)
- Switch to a GTP-U eBPF module which does not have these short comings: work has begun under this Pull Request but I had not the time to continue working on this feature: https://github.com/HewlettPackard/PacketRusher/pull/47

If I can be of any help and can help clarify anything, please say so.

Thanks a lot!
Valentin

**Comment by BENHSU0723** [comment]
Thanks your reply, @linouxis9 . It helps a lot. I may  try to develop some features on branch [[ebpf](https://github.com/HewlettPackard/PacketRusher/tree/ebpf)]. I just tried to run some tests, it's turely a feasible solution towards my problem. 

BRs, Ben.

**Comment by linouxis9** [comment]
Thanks a lot @BENHSU0723! If you manage to go far enough, please do open a PR, it would be truly appreciated!

Thanks and cheers,
Valentin
